services:
  - type: web
    name: smart-vaccine-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ADMIN_CREATION_SECRET
        sync: false
      - key: RENDER
        value: "true"

  - type: web
    name: smart-vaccine-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    rootDir: client
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false